name: Performance-Test

on:
  push:
    branches:
      - development

jobs:
  setup:
    name: Artillery Performance Test
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_PREFIX: "~/.npm-global"
      STAGE_NAME: merge-perf-test

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true

      - name: nodeJS and npm version
        run: npm -v
      - name: npm init
        run: npm init -y
      - name: Install artillery
        run: npm install -g artillery
      - name: Sleep
        run: sleep 10s
      - name: Create Test Directory
        run: mkdir -p /home/runner/work/_temp/artilleryTestReportsDir
      - name: Running Artillery Test
        run: /home/runner/.npm-global/lib/node_modules/artillery/bin/artillery run --output /home/runner/work/_temp/artilleryTestReportsDir/artilleryReport_$(date '+%Y-%m-%d-%H-%M-%S').json ./testing/artillery/githubaction_url_performance.yml
      - name: uploading to Azure Blob Storage 
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: '/home/runner/work/_temp/artilleryTestReportsDir'
          container_name: 'artillery'
          connection_string: ${{ secrets.AZ_BLOB_CONNECTION_STRING_ARTILLERY }}
          extra_args: '--pattern artilleryReport_20*.json'
          sync: false