name: Performance-Test

on:
  [push]
  #branches:
  #  - development

jobs:
  setup:
    name: slsart Performance Test
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_PREFIX: "~/.npm-global"
      STAGE_NAME: merge-perf-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      
      - name: nodeJS and npm version
        run: npm -v
      - name: npm init
        run: npm init -y
      - name: Install artillery
        run: npm install -g artillery
      - name: Sleep
        run: sleep 10s
      - name: version test
        run: /home/runner/.npm-global/lib/node_modules/artillery/bin/artillery run --output artilleryReport.json./testing/artillery/githubaction_url_performance.yml
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --account-name <STORAGE_ACCOUNT_NAME> -d '$web' -s .
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name "CDN_PROFILE_NAME" --name "CDN_ENDPOINT" --resource-group "RESOURCE_GROUP"

    # Azure logout 
      - name: logout
        run: |
            az logout 

    
    # examples for future:
    # - run: cp ./slsart/script.yml ./
    #    run: cp ./slsart/serverless.yml ./
    #- name: Deploy, invoke, remove functions
    