name: Load testing  /users/{user_id}/tasks

on:
  push:
    branches: developement

jobs:
  slsart-perf:
    name: slsart Performance Test
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_PREFIX: "~/.npm-global"
      STAGE_NAME: merge-perf-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Install serverless and serverless-artillery
        run: |
          npm install -g serverless@1.38.0 serverless-artillery
      # once a folder with slsart script.yml and serverless.yml are created and in the repo
      # we can copy them into the working dir to run those specific tests with those configurations
      # - currently this just runs the defaults
      # examples for future:
      #- run: cp ./slsart/script.yml ./
      # - run: cp ./slsart/serverless.yml ./

      - name: Deploy, invoke, remove functions
        run: |
          ~/.npm-global/bin/slsart deploy --stage $STAGE_NAME 
          ~/.npm-global/bin/slsart invoke -s ../../testing/Serverless-Artillery/test-users-userid-tasks.yml --stage $STAGE_NAME > ../../testing/results/users-userid-tasks.json
          ~/.npm-global/bin/slsart remove --stage $STAGE_NAME
